### ISSUE TITLE
Create a working directory parameter and use it if set

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/action-autotag#12]
For monorepos.
```
  workdir:
    description: 'Directory with the code to tag'
    required: false
    default: '.'
```
```
  steps:
    - id: tag
      name: Tag
      run: ...
      working-directory: ${{ inputs.workdir }}
      shell: bash
```
