### ISSUE TITLE
Make tag 'v' prefix optional but on by default

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/action-autotag#14]
Autotag by default does not output the v prefix which is somewhat confusing behavior but we work with it, and this workflow includes it by default. We should continue to do so, but provide the option to keep to autotag's default bare version.

```
inputs:
  tag-prepend:
    description: ''Default string tag is prepended with"
    required: false
    default: "v"
```
